inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/*.rb

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineAssignmentLayout:
  Enabled: true

Style/MultilineHashBraceLayout:
  Enabled: true

Style/MultilineMethodCallBraceLayout:
  Enabled: true

Style/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Style/StringMethods:
  Enabled: true

Rails/Output:
  Exclude:
    - db/seeds.rb
